// CLI: create a draft PR if one doesn't already exist for the branch.
// Usage: node .agent/dist/cli/create-pr.js
// Env: BRANCH, BASE_BRANCH, PR_TITLE, PR_BODY, PR_KIND, ISSUE_NUMBER,
//      REQUESTED_BY, RUBRICS_REF
// Outputs: pr_url, pr_number

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { randomBytes } from "node:crypto";
import { findExistingPr, createPr } from "../github.js";
import { setOutput } from "../output.js";

const branch = process.env.BRANCH || "";
const baseBranch = process.env.BASE_BRANCH || "main";
const issueNumber = process.env.ISSUE_NUMBER || "";
const requestedBy = process.env.REQUESTED_BY || "";
const prKind = process.env.PR_KIND || "";
const rubricsRef = process.env.RUBRICS_REF || "agent/rubrics";

function parsePrNumber(prUrl: string): string {
  const match = prUrl.match(/\/pull\/(\d+)(?:[/?#].*)?$/);
  return match ? match[1] : "";
}

function defaultTitle(): string {
  if (prKind === "add-rubrics") return "Propose rubric updates";
  return `feat: implement #${issueNumber}`;
}

function defaultBody(): string {
  if (prKind === "add-rubrics") {
    return [
      `Proposes rubric updates targeting \`${rubricsRef}\`.`,
      "",
      issueNumber ? `Source target: #${issueNumber}.` : "",
      requestedBy ? `Requested by @${requestedBy}.` : "",
      "Generated by the `agent-add-rubrics` workflow.",
    ].filter(Boolean).join("\n");
  }

  return [
    `Implements #${issueNumber}.`,
    "",
    requestedBy ? `Requested by @${requestedBy}.` : "",
    "Generated by the `agent-implement` workflow using Codex.",
  ].filter(Boolean).join("\n");
}

// Check for existing PR first
const existing = findExistingPr(branch);
if (existing) {
  setOutput("pr_url", existing);
  setOutput("pr_number", parsePrNumber(existing));
  console.log(`Existing PR found: ${existing}`);
  process.exit(0);
}

// Build title and body
const title = process.env.PR_TITLE || defaultTitle();
const body = process.env.PR_BODY || defaultBody();

const runnerTemp = process.env.RUNNER_TEMP || "/tmp";
const bodyFile = join(runnerTemp, `pr-body-${randomBytes(8).toString("hex")}.md`);
writeFileSync(bodyFile, body + "\n", "utf8");

const prUrl = createPr({
  base: baseBranch,
  head: branch,
  title,
  bodyFile,
  draft: true,
});

setOutput("pr_url", prUrl);
setOutput("pr_number", parsePrNumber(prUrl));
console.log(`PR created: ${prUrl}`);
