import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { test } from "node:test";
import { strict as assert } from "node:assert";

const repoRoot = resolve(__dirname, "../../..");

function writeExecutable(path: string, content: string): void {
  writeFileSync(path, content, { encoding: "utf8", mode: 0o755 });
}

test("create-pr uses add-rubrics fallback metadata without implement wording", () => {
  const tempDir = mkdtempSync(join(tmpdir(), "create-pr-"));

  try {
    const binDir = join(tempDir, "bin");
    const logPath = join(tempDir, "gh.log");
    const bodyCopy = join(tempDir, "body.md");
    const outputPath = join(tempDir, "outputs.txt");
    mkdirSync(binDir);

    writeExecutable(join(binDir, "gh"), [
      "#!/usr/bin/env bash",
      "set -euo pipefail",
      "printf '%s\\n' \"$*\" >> \"$FAKE_GH_LOG\"",
      "if [ \"$1\" = \"pr\" ] && [ \"$2\" = \"list\" ]; then",
      "  exit 0",
      "fi",
      "if [ \"$1\" = \"pr\" ] && [ \"$2\" = \"create\" ]; then",
      "  body_file=\"\"",
      "  while [ \"$#\" -gt 0 ]; do",
      "    if [ \"$1\" = \"--body-file\" ]; then",
      "      shift",
      "      body_file=\"$1\"",
      "    fi",
      "    shift || true",
      "  done",
      "  cp \"$body_file\" \"$FAKE_BODY_COPY\"",
      "  printf 'https://github.com/self-evolving/repo/pull/99\\n'",
      "  exit 0",
      "fi",
      "printf 'unexpected gh args: %s\\n' \"$*\" >&2",
      "exit 1",
      "",
    ].join("\n"));

    const result = spawnSync("node", [".agent/dist/cli/create-pr.js"], {
      cwd: repoRoot,
      env: {
        ...process.env,
        BASE_BRANCH: "agent/rubrics",
        BRANCH: "agent/add-rubrics-issue-381/request-abc123",
        FAKE_BODY_COPY: bodyCopy,
        FAKE_GH_LOG: logPath,
        GITHUB_OUTPUT: outputPath,
        ISSUE_NUMBER: "381",
        PATH: `${binDir}:${process.env.PATH || ""}`,
        PR_BODY: "",
        PR_KIND: "add-rubrics",
        PR_TITLE: "",
        REQUESTED_BY: "lolipopshock",
        RUBRICS_REF: "agent/rubrics",
        RUNNER_TEMP: tempDir,
      },
      encoding: "utf8",
    });

    assert.equal(result.status, 0, result.stderr);
    const body = readFileSync(bodyCopy, "utf8");
    assert.match(body, /Proposes rubric updates targeting `agent\/rubrics`/);
    assert.match(body, /Source target: #381/);
    assert.match(body, /Requested by @lolipopshock/);
    assert.match(body, /Generated by the `agent-add-rubrics` workflow/);
    assert.doesNotMatch(body, /Implements #381/);
    assert.doesNotMatch(body, /agent-implement/);

    const log = readFileSync(logPath, "utf8");
    assert.match(log, /pr create/);
    assert.match(log, /--title Propose rubric updates/);
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
});
